import { useCallback, useEffect, useMemo, useState } from 'react';
import { useAuth } from '../../context/AuthContext.jsx';
import { getAllApplications } from '../../api/applicationApi.js';
import { getAllVerifications, createVerification, updateVerification } from '../../api/verificationApi.js';
import VerificationForm from '../../components/verifications/VerificationForm.jsx';
import VerificationTable from '../../components/verifications/VerificationTable.jsx';
const VERIFICATION_ROLES = new Set(['ADMIN', 'FIELD_OFFICER', 'DISTRICT_OFFICER']);
function getApiErrorMessage(error, fallback) { const data = error?.response?.data; if (data?.message) return data.message; if (data?.error && typeof data.error === 'string') return data.error; if (error?.response?.status === 401) return 'Your session has expired. Please sign in again.'; if (error?.response?.status === 403) return 'You do not have permission to perform this action.'; if (error?.response?.status === 404) return 'The application or verification record was not found.'; if (error?.response?.status === 409) return 'A verification record already exists for this application.'; if (error?.response?.status === 400) return 'Please check the verification details and try again.'; return fallback; }
export default function VerificationManagement() {
  const { role, userId } = useAuth(); const canManage = VERIFICATION_ROLES.has(role);
  const [verifications, setVerifications] = useState([]); const [applications, setApplications] = useState([]); const [loading, setLoading] = useState(true); const [pageError, setPageError] = useState(''); const [actionMessage, setActionMessage] = useState(''); const [search, setSearch] = useState(''); const [formOpen, setFormOpen] = useState(false); const [submitting, setSubmitting] = useState(false); const [updatingId, setUpdatingId] = useState(null);
  const loadData = useCallback(async () => { setLoading(true); setPageError(''); try { const [verificationResponse, applicationResponse] = await Promise.all([getAllVerifications(), getAllApplications()]); setVerifications(Array.isArray(verificationResponse.data) ? verificationResponse.data : []); setApplications(Array.isArray(applicationResponse.data) ? applicationResponse.data : []); } catch (error) { setPageError(getApiErrorMessage(error, 'Unable to load verification data.')); } finally { setLoading(false); } }, []);
  useEffect(() => { loadData(); }, [loadData]);
  const pendingApplications = useMemo(() => { const ids = new Set(verifications.map((v) => v.applicationId)); return applications.filter((a) => a.status === 'UNDER_VERIFICATION' && !ids.has(a.id)); }, [applications, verifications]);
  const filteredVerifications = useMemo(() => { const q = search.trim().toLowerCase(); if (!q) return verifications; return verifications.filter((v) => [v.id, v.applicationId, v.verifiedById, v.status, v.remarks, v.verifiedAt].filter((x) => x !== null && x !== undefined).some((x) => String(x).toLowerCase().includes(q))); }, [verifications, search]);
  const handleCreate = async (request) => { setSubmitting(true); setPageError(''); setActionMessage(''); try { await createVerification(request); setFormOpen(false); setActionMessage(`Verification saved successfully for application #${request.applicationId}.`); await loadData(); } catch (error) { setPageError(getApiErrorMessage(error, 'Unable to save verification.')); } finally { setSubmitting(false); } };
  const handleUpdate = async (verification, status) => { if (!window.confirm(`Change verification #${verification.id} to ${status.replace('_', ' ')}?`)) return; setUpdatingId(verification.id); setPageError(''); setActionMessage(''); try { await updateVerification(verification.id, { status }); setActionMessage(`Verification #${verification.id} updated successfully.`); await loadData(); } catch (error) { setPageError(getApiErrorMessage(error, 'Unable to update verification.')); } finally { setUpdatingId(null); } };
  return <div className="module-page"><div className="module-page-header"><div><span className="eyebrow">VERIFICATION MANAGEMENT</span><h1>Verification</h1><p>Review applications that reached the verification stage and record the field verification outcome.</p></div>{canManage && !formOpen && <button type="button" className="btn-primary header-action-button" onClick={() => { setActionMessage(''); setPageError(''); setFormOpen(true); }}>+ New Verification</button>}</div>
    {actionMessage && <div className="success-banner">{actionMessage}</div>}{pageError && <div className="form-error module-error" role="alert">{pageError}<button type="button" className="error-dismiss" onClick={() => setPageError('')} aria-label="Dismiss error">×</button></div>}
    {formOpen && <VerificationForm applications={pendingApplications} userId={userId} onSubmit={handleCreate} onCancel={() => !submitting && setFormOpen(false)} submitting={submitting} />}
    <section className="verification-queue-card"><div className="queue-summary"><div><span className="eyebrow">READY FOR ACTION</span><strong>{pendingApplications.length}</strong><span>application{pendingApplications.length === 1 ? '' : 's'} under verification</span></div><p>Only applications with backend status <strong>UNDER_VERIFICATION</strong> and no existing verification record are offered for a new verification.</p></div></section>
    <section className="verification-list-card"><div className="section-heading verification-list-heading"><div><h2>Verification Records</h2><p>{verifications.length} record{verifications.length === 1 ? '' : 's'} found</p></div><div className="scheme-search"><label htmlFor="verification-search">Search verifications</label><input id="verification-search" type="search" placeholder="Search ID, application, status…" value={search} onChange={(event) => setSearch(event.target.value)} /></div></div>{loading ? <div className="loading-state">Loading verification records...</div> : <VerificationTable verifications={filteredVerifications} canManage={canManage} updatingId={updatingId} onUpdate={handleUpdate} />}</section>
    <p className="workflow-note"><strong>Workflow:</strong> UNDER_VERIFICATION → VERIFIED or REJECTED. A VERIFIED application becomes available to the next approval stage according to the backend workflow.</p>
  </div>;
}
